### ISSUE TITLE
Issue after uninstalling

### ISSUE THREAD

**Issue by hvitis** [ryu1kn/vscode-put-print#5]
I uninstalled the extension on Mac and I cannot use the shift plus x. I get command is not available message although I am not using this command anywhere. Any idea how to fix it. I dont want to uninstall vscode again

**Comment by hvitis** [comment]
I found keybindings.json with custom settings that was located in ANTOHER repo. I am not sure how on earth vscode was loading those, fortunately works now.

**Comment by ryu1kn** [comment]
Hi @hvitis , not sure what's happening on your vscode. This extension adds below keyboard shortcuts but not `Shift + x`

https://github.com/ryu1kn/vscode-put-print/blob/3636103fb626d3b8a1d5a15f2fcb0a2aca47df83/package.json#L113-L124

**Comment by hvitis** [comment]
It might have been my fault yes but still never happened to me with any other app.
